### ISSUE TITLE
ERROR: Encountered errors while bringing up the project.

### ISSUE THREAD

**Issue by pingyangtiaer** [PacktPublishing/Hands-on-Microservices-with-Python#2]
I ran 
docker-compose -f docker-compose.deploy.yml up -d
and I got error in 
Creating frontendgit_frontend_1   ... error:
ERROR: for frontend  Cannot start service frontend: driver failed programming external connectivity on endpoint frontendgit_frontend_1 (8b311ac1529ffb79ec8a735fe7eed33565c47120089d341378f602599c1e47f3): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.
I am running the script on the VPS (and I don't think I have other container is using the port 80, if I do a docker container ls, I got:
"""
CONTAINER ID        IMAGE                 COMMAND                  CREATED              STATUS              PORTS                    NAMES
8fb252ab24b5        frontendgit_product   "python app.py"          About a minute ago   Up About a minute   0.0.0.0:8081->5000/tcp   frontendgit_product_1
481dc6b0fb7d        frontendgit_order     "python app.py"          About a minute ago   Up About a minute   0.0.0.0:8083->5000/tcp   frontendgit_order_1
31da7153dfec        frontendgit_user      "python app.py"          About a minute ago   Up About a minute   0.0.0.0:8082->5000/tcp   frontendgit_user_1
e6e181f30443        mysql:5.7.22          "docker-entrypoint.s…"   About a minute ago   Up About a minute   3306/tcp                 frontendgit_product_db_1
909312909afc        mysql:5.7.22          "docker-entrypoint.s…"   About a minute ago   Up About a minute   3306/tcp                 frontendgit_user_db_1
4d79b434f60a        mysql:5.7.22          "docker-entrypoint.s…"   About a minute ago   Up About a minute   3306/tcp                 frontendgit_order_db_1
"""
Any idea?

**Comment by pfwd** [comment]
Hi, I discussed this issue in a recent live coding stream (https://youtu.be/5EpsA2raV0k) so others with the same issue can be pointed in the right direction.

In short, the solution is to check that nothing else is assigned to port 80.  This isn't just limited to containers.  If you had a LAMP stack running in the VPS you would get the same issue.

I recommend using Docker machine instead of your own VPS as this is a clean Docker environment.
I have some tutorials on Docker Machine here: https://youtu.be/RA4vAJSMtEc

As I cannot replicate this issue I need to close it but I hope this helps
